# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB youtube_data
ENV POSTGRES_USER your_username
ENV POSTGRES_PASSWORD your_password

# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command for the container
CMD ["postgres"]
